export const assemblyColors = {
    'La République en Marche': '#E1B000',
    'Mouvement Démocrate': '#FFBE3F',
    'Mouvement Démocrate (MoDem) et Démocrates apparentés': '#FFBE3F',
    'Mouvement Démocrate et apparentés': '#FFBE3F',
    'Les Constructifs : républicains, UDI, indépendants': '#6387A8',
    'Les Constructifs : républicains, UDI, indépendants': '#6387A8',
    'Libertés et Territoires': '#6387A8',
    'Socialistes et apparentés': '#FF7999',
    'UDI et Indépendants': '#6EB3E9',
    'Les Républicains': '#0890C5',
    'Gauche démocrate et républicaine': '#DA679E',
    'Non inscrits': '#cccccc',
    'La France insoumise': '#FF3333',
    'Nouvelle Gauche': '#DA679E',
    'Agir ensemble': '#E1B000',
    'Agir Ensemble': '#E1B000'
};

export const colors = {
    LRM: '#E1B000',
    MoDem: '#FFBE3F',
    'Hor.': '#E1B000',
    UL: '#E1B000',
    Tapura: '#E1B000',
    GUSR: '#E1B000',
    Agir: '#E1B000',
    'div. c.': '#E1B000',
    'LRM dis.': '#E1B000',
    'MoDem dis.': '#FFBE3F',
    'Hor. Dis.': '#E1B000',
    PRV: '#E1B000',
    'Anim.': '#85D693',
    '\u00e9col.': '#85D693',
    EAC: '#85D693',
    UDMF: '#957CB5',
    'div.': '#957CB6',
    Pirate: '#957CB7',
    MdR: '#957CB8',
    'souv.': '#957CB9',
    'LR dis.': '#6387A8',
    'div. d.': '#6387A8',
    'LCen.': '#6387A8',
    'R\u00e9s.': '#6387A8',
    Ensemble: '#FF9F0E',
    'PRV-Ensemble': '#FF9F0E',
    'LRM-Ensemble': '#FF9F0E',
    'MoDem-Ensemble': '#FF9F0E',
    'Hor.-Ensemble': '#FF9F0E',
    'PS-Ensemble': '#FF9F0E',
    'div. c.-Ensemble': '#FF9F0E',
    'UDI-Ensemble': '#FF9F0E',
    'div. d.-Ensemble': '#FF9F0E',
    'Agir-Ensemble': '#FF9F0E',
    'GUSR-Ensemble': '#FF9F0E',
    'Tapura-Ensemble': '#FF9F0E',
    'UL-Ensemble': '#FF9F0E',
    DLF: '#654519',
    'Pat.': '#654519',
    'ext. d.': '#654519',
    LO: '#D03232',
    NPA: '#D03232',
    POI: '#D03232',
    POID: '#D03232',
    'ext. g.': '#D03232',
    PCF: '#FF3333',
    LFI: '#FF3333',
    PS: '#FF7999',
    PRG: '#DA679E',
    'div. g.': '#DA679E',
    'Gen.': '#DA679E',
    MdP: '#DA679E',
    PCR: '#FF3333',
    PLR: '#DA679E',
    RR: '#DA679Ea',
    'LFI dis.': '#FF3333',
    'PCF dis.': '#FF3333',
    'PS dis.': '#FF7999',
    'EELV dis.': '#23B73D',
    GE: '#23B73D',
    EELV: '#23B73D',
    UDI: '#6EB3E9',
    LR: '#0890C5',
    Nupes: '#A11870',
    'div. g.-Nupes': '#A11870',
    'LFI-Nupes': '#A11870',
    'PCF-Nupes': '#A11870',
    'PS-Nupes': '#A11870',
    'EELV-Nupes': '#A11870',
    'Gen.-Nupes': '#A11870',
    '\u00e9col.-Nupes': '#A11870',
    'GE-Nupes': '#A11870',
    'ind.-Nupes': '#A11870',
    'Tavini-Nupes': '#A11870',
    RN: '#8D6026',
    'Rec.': '#654519',
    'r\u00e9g.': '#78668D',
    'Ab.': '#78668D',
    'aut.': '#78668D',
    FLNKS: '#78668D',
    'ind.': '#78668D',
    MIM: '#78668D',
    PPDG: '#78668D',
    "Amuitahira'a": '#78668D',
    Tavini: '#78668D',
    'Wal.': '#78668D',
    UDB: '#78668D',
    'r\u00e9g.-RPS': '#78668D',
    'Ab.-RPS': '#78668D',
    Femu: '#78668D',
    'Femu-RPS': '#78668D',
    PNC: '#78668D',
    'PNC-RPS': '#78668D',
    PO: '#78668D',
    'PO-RPS': '#78668D',
    Unser: '#78668D',
    'Unser-RPS': '#78668D',
    MRS: '#78668D',
    'MRS-RPS': '#78668D',
    'UDB-RPS': '#78668D',
    FGR: '#DA679E'
};

export const groups = {
    LRM: 'Centre',
    MoDem: 'Centre',
    'Hor.': 'Centre',
    UL: 'Centre',
    Tapura: 'Centre',
    GUSR: 'Centre',
    Agir: 'Centre',
    'div. c.': 'Centre',
    'LRM dis.': 'Centre',
    'MoDem dis.': 'Centre',
    'Hor. Dis.': 'Centre',
    PRV: 'Centre',
    'Anim.': 'Divers',
    '\u00e9col.': 'Divers',
    EAC: 'Divers',
    UDMF: 'Divers',
    'div.': 'Divers',
    Pirate: 'Divers',
    MdR: 'Divers',
    'souv.': 'Divers',
    'LR dis.': 'Droite',
    'div. d.': 'Droite',
    'LCen.': 'Droite',
    'R\u00e9s.': 'Droite',
    Ensemble: 'Ensemble',
    'PRV-Ensemble': 'Ensemble',
    'LRM-Ensemble': 'Ensemble',
    'MoDem-Ensemble': 'Ensemble',
    'Hor.-Ensemble': 'Ensemble',
    'PS-Ensemble': 'Ensemble',
    'div. c.-Ensemble': 'Ensemble',
    'UDI-Ensemble': 'Ensemble',
    'div. d.-Ensemble': 'Ensemble',
    'Agir-Ensemble': 'Ensemble',
    'GUSR-Ensemble': 'Ensemble',
    'Tapura-Ensemble': 'Ensemble',
    'UL-Ensemble': 'Ensemble',
    DLF: 'Extr\u00eame droite',
    'Pat.': 'Extr\u00eame droite',
    'ext. d.': 'Extr\u00eame droite',
    LO: 'Extr\u00eame gauche',
    NPA: 'Extr\u00eame gauche',
    POI: 'Extr\u00eame gauche',
    POID: 'Extr\u00eame gauche',
    'ext. g.': 'Extr\u00eame gauche',
    PCF: 'Gauche',
    LFI: 'Gauche',
    PS: 'Gauche',
    PRG: 'Gauche',
    'div. g.': 'Gauche',
    'Gen.': 'Gauche',
    MdP: 'Gauche',
    PCR: 'Gauche',
    PLR: 'Gauche',
    RR: 'Gauche',
    'LFI dis.': 'Gauche',
    'PCF dis.': 'Gauche',
    'PS dis.': 'Gauche',
    'EELV dis.': 'Gauche',
    GE: 'Gauche',
    EELV: 'Gauche',
    UDI: 'LR-UDI',
    LR: 'LR-UDI',
    Nupes: 'Nupes',
    'div. g.-Nupes': 'Nupes',
    'LFI-Nupes': 'Nupes',
    'PCF-Nupes': 'Nupes',
    'PS-Nupes': 'Nupes',
    'EELV-Nupes': 'Nupes',
    'Gen.-Nupes': 'Nupes',
    '\u00e9col.-Nupes': 'Nupes',
    'GE-Nupes': 'Nupes',
    'ind.-Nupes': 'Nupes',
    'Tavini-Nupes': 'Nupes',
    RN: 'Rassemblement national',
    'Rec.': 'Reconqu\u00eate',
    'r\u00e9g.': 'R\u00e9gionalistes',
    'Ab.': 'R\u00e9gionalistes',
    'aut.': 'R\u00e9gionalistes',
    FLNKS: 'R\u00e9gionalistes',
    'ind.': 'R\u00e9gionalistes',
    MIM: 'R\u00e9gionalistes',
    PPDG: 'R\u00e9gionalistes',
    "Amuitahira'a": 'R\u00e9gionalistes',
    Tavini: 'R\u00e9gionalistes',
    'Wal.': 'R\u00e9gionalistes',
    UDB: 'R\u00e9gionalistes',
    'r\u00e9g.-RPS': 'R\u00e9gionalistes',
    'Ab.-RPS': 'R\u00e9gionalistes',
    Femu: 'R\u00e9gionalistes',
    'Femu-RPS': 'R\u00e9gionalistes',
    PNC: 'R\u00e9gionalistes',
    'PNC-RPS': 'R\u00e9gionalistes',
    PO: 'R\u00e9gionalistes',
    'PO-RPS': 'R\u00e9gionalistes',
    Unser: 'R\u00e9gionalistes',
    'Unser-RPS': 'R\u00e9gionalistes',
    MRS: 'R\u00e9gionalistes',
    'MRS-RPS': 'R\u00e9gionalistes',
    'UDB-RPS': 'R\u00e9gionalistes',
    FGR: 'Gauche'
};
