on:
  create:
    tags:
      - v*
env:
  GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
  GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup - node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      - name: Build Next.js
        run: npm run build
      - name: Deploy to GCP
        run: |-
          gsutil -m -h 'Cache-Control: max-age=31536000' rsync -R out gs://$GCP_BUCKET
