on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build
        run: |
          npm install
          npm run build
      - name: Build Image & Push to Docker Registry
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/jeremie/quel-depute:staging . -f devops/Dockerfile
          docker image push --all-tags ${{ secrets.DOCKER_REGISTRY }}/jeremie/quel-depute
      - name: SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          ssh debian@${{ secrets.DEPLOY_HOST }}  "bash -s" < devops/deploy-staging.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}